spring:
  application:
    name: shipping-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

kafka:
  listener:
    concurrency: ${KAFKA_CONCURRENCY:3}
server:
  port: 8083

dlt:
  replay:
    enabled: false
    max-retries: 3