spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      enable-auto-commit: false

kafka:
  listener:
    concurrency: ${KAFKA_CONCURRENCY:4}
  producer:
    wait-acks: true
    send-timeout-ms: 5000
server:
  port: 8082

dlt:
  replay:
    enabled: false
    max-retries: 3